export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const FETCH_KEYWORD = 'FETCH_KEYWORD';
export const FETCH_SUCCEEDED = 'FETCH_SUCCEEDED';
export const FETCH_FAILD = 'FETCH_FAILD';

export const GET_HOTELS = 'GET_HOTELS';
export const GET_HOTELS_SUCCEEDED = 'GET_HOTELS_SUCCEEDED';
export const GET_HOTELS_FAILD = 'GET_HOTELS_FAILD';

export const GET_INFOR_HOTEL = 'GET_INFOR_HOTEL';
export const GET_INFOR_HOTEL_SUCCEEDED = 'GET_INFOR_HOTEL_SUCCEEDED';
export const GET_INFOR_HOTEL_FAILD = 'GET_INFOR_HOTEL_FAILD';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE LOADING';