export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE LOADING';

export const FETCH_KEYWORD = 'FETCH_KEYWORD';
export const FETCH_SUCCEEDED = 'FETCH_SUCCEEDED';
export const FETCH_FAILD = 'FETCH_FAILD';

export const GET_HOTELS = 'GET_HOTELS';
export const GET_HOTELS_SUCCEEDED = 'GET_HOTELS_SUCCEEDED';
export const GET_HOTELS_FAILD = 'GET_HOTELS_FAILD';

export const GET_INFOR_HOTEL = 'GET_INFOR_HOTEL';
export const GET_INFOR_HOTEL_SUCCEEDED = 'GET_INFOR_HOTEL_SUCCEEDED';
export const GET_INFOR_HOTEL_FAILD = 'GET_INFOR_HOTEL_FAILD';

export const PRICE_ONE_NIGTH = 'PRICE_ONE_NIGTH';
export const STAR_HOTEL = 'STAR_HOTEL';
export const OVERALL_SCORE = 'OVERALL_SCORE';
export const SERVICE_HOTEL = 'SERVICE_HOTEL';
export const APPLY = 'APPLY';

export const GET_ALL_PRICE = 'GET_ALL_PRICE';
export const GET_ALL_PRICE_SUCCESS = 'GET_ALL_PRICE_SUCCESS'; 
export const GET_ALL_PRICE_FAILD = 'GET_ALL_PRICE_FAILD'; 

export const SORT_PRICE_ASC = 'SORT_PRICE_ASC';
 
export const GET_MIN_PRICE = 'GET_MIN_PRICE';

